# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(70, 30, 251, 191))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.task_name = QtWidgets.QLineEdit(self.widget)
        self.task_name.setObjectName("task_name")
        self.gridLayout.addWidget(self.task_name, 0, 0, 1, 1)
        self.task_desc = QtWidgets.QLineEdit(self.widget)
        self.task_desc.setObjectName("task_desc")
        self.gridLayout.addWidget(self.task_desc, 1, 0, 1, 1)
        self.priority_box = QtWidgets.QComboBox(self.widget)
        self.priority_box.setObjectName("priority_box")
        self.gridLayout.addWidget(self.priority_box, 2, 0, 1, 1)
        self.apply_button = QtWidgets.QPushButton(self.widget)
        self.apply_button.setObjectName("apply_button")
        self.gridLayout.addWidget(self.apply_button, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.apply_button.setText(_translate("Dialog", "PushButton"))
