# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 350)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(Dialog)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.name_label = QtWidgets.QLabel(Dialog)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_label)
        self.task_name = QtWidgets.QLineEdit(Dialog)
        self.task_name.setObjectName("task_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.task_name)
        self.desc_label = QtWidgets.QLabel(Dialog)
        self.desc_label.setAlignment(QtCore.Qt.AlignTop)
        self.desc_label.setObjectName("desc_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.desc_label)
        self.task_desc = QtWidgets.QTextEdit(Dialog)
        self.task_desc.setMinimumSize(QtCore.QSize(0, 100))
        self.task_desc.setMaximumSize(QtCore.QSize(16777215, 150))
        self.task_desc.setObjectName("task_desc")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.task_desc)
        self.priority_label = QtWidgets.QLabel(Dialog)
        self.priority_label.setObjectName("priority_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.priority_label)
        self.priority_box = QtWidgets.QComboBox(Dialog)
        self.priority_box.setObjectName("priority_box")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.priority_box)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.button_layout.addItem(spacerItem1)
        self.apply_button = QtWidgets.QPushButton(Dialog)
        self.apply_button.setDefault(True)
        self.apply_button.setObjectName("apply_button")
        self.button_layout.addWidget(self.apply_button)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.button_layout.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.button_layout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавить задачу"))
        self.title_label.setText(_translate("Dialog", "Новая задача"))
        self.title_label.setStyleSheet(_translate("Dialog", "font-size: 14px; font-weight: bold; margin: 10px;"))
        self.name_label.setText(_translate("Dialog", "Название:"))
        self.task_name.setPlaceholderText(_translate("Dialog", "Введите название задачи"))
        self.desc_label.setText(_translate("Dialog", "Описание:"))
        self.task_desc.setPlaceholderText(_translate("Dialog", "Введите описание задачи (необязательно)"))
        self.priority_label.setText(_translate("Dialog", "Приоритет:"))
        self.priority_box.setToolTip(_translate("Dialog", "1 - самый высокий приоритет, 5 - самый низкий"))
        self.apply_button.setText(_translate("Dialog", "Добавить"))
        self.cancel_button.setText(_translate("Dialog", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
