# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task_details_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaskDetailsDialog(object):
    def setupUi(self, TaskDetailsDialog):
        TaskDetailsDialog.setObjectName("TaskDetailsDialog")
        TaskDetailsDialog.resize(500, 400)
        TaskDetailsDialog.setMinimumSize(QtCore.QSize(400, 300))
        TaskDetailsDialog.setModal(True)
        self.centralwidget = QtWidgets.QWidget(TaskDetailsDialog)
        self.centralwidget.setGeometry(QtCore.QRect(10, 10, 480, 380))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.id_label = QtWidgets.QLabel(self.centralwidget)
        self.id_label.setObjectName("id_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.id_label)
        self.id_value = QtWidgets.QLabel(self.centralwidget)
        self.id_value.setObjectName("id_value")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.id_value)
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setObjectName("title_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.title_label)
        self.title_value = QtWidgets.QLabel(self.centralwidget)
        self.title_value.setWordWrap(True)
        self.title_value.setObjectName("title_value")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.title_value)
        self.priority_label = QtWidgets.QLabel(self.centralwidget)
        self.priority_label.setObjectName("priority_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.priority_label)
        self.priority_value = QtWidgets.QLabel(self.centralwidget)
        self.priority_value.setObjectName("priority_value")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.priority_value)
        self.created_label = QtWidgets.QLabel(self.centralwidget)
        self.created_label.setObjectName("created_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.created_label)
        self.created_value = QtWidgets.QLabel(self.centralwidget)
        self.created_value.setObjectName("created_value")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.created_value)
        self.description_label = QtWidgets.QLabel(self.centralwidget)
        self.description_label.setAlignment(QtCore.Qt.AlignTop)
        self.description_label.setObjectName("description_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.description_label)
        self.description_value = QtWidgets.QTextEdit(self.centralwidget)
        self.description_value.setReadOnly(True)
        self.description_value.setMinimumSize(QtCore.QSize(0, 150))
        self.description_value.setObjectName("description_value")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.description_value)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.button_layout.addItem(spacerItem1)
        self.edit_button = QtWidgets.QPushButton(self.centralwidget)
        self.edit_button.setObjectName("edit_button")
        self.button_layout.addWidget(self.edit_button)
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setObjectName("delete_button")
        self.button_layout.addWidget(self.delete_button)
        self.close_button = QtWidgets.QPushButton(self.centralwidget)
        self.close_button.setObjectName("close_button")
        self.button_layout.addWidget(self.close_button)
        self.verticalLayout.addLayout(self.button_layout)

        self.retranslateUi(TaskDetailsDialog)
        QtCore.QMetaObject.connectSlotsByName(TaskDetailsDialog)

    def retranslateUi(self, TaskDetailsDialog):
        _translate = QtCore.QCoreApplication.translate
        TaskDetailsDialog.setWindowTitle(_translate("TaskDetailsDialog", "Подробности задачи"))
        self.id_label.setText(_translate("TaskDetailsDialog", "ID:"))
        self.id_label.setStyleSheet(_translate("TaskDetailsDialog", "font-weight: bold;"))
        self.id_value.setText(_translate("TaskDetailsDialog", "-"))
        self.title_label.setText(_translate("TaskDetailsDialog", "Название:"))
        self.title_label.setStyleSheet(_translate("TaskDetailsDialog", "font-weight: bold;"))
        self.title_value.setText(_translate("TaskDetailsDialog", "-"))
        self.priority_label.setText(_translate("TaskDetailsDialog", "Приоритет:"))
        self.priority_label.setStyleSheet(_translate("TaskDetailsDialog", "font-weight: bold;"))
        self.priority_value.setText(_translate("TaskDetailsDialog", "-"))
        self.created_label.setText(_translate("TaskDetailsDialog", "Создана:"))
        self.created_label.setStyleSheet(_translate("TaskDetailsDialog", "font-weight: bold;"))
        self.created_value.setText(_translate("TaskDetailsDialog", "-"))
        self.description_label.setText(_translate("TaskDetailsDialog", "Описание:"))
        self.description_label.setStyleSheet(_translate("TaskDetailsDialog", "font-weight: bold;"))
        self.edit_button.setText(_translate("TaskDetailsDialog", "Редактировать"))
        self.delete_button.setText(_translate("TaskDetailsDialog", "Удалить"))
        self.delete_button.setStyleSheet(_translate("TaskDetailsDialog", "QPushButton { background-color: #ff4444; color: white; }"))
        self.close_button.setText(_translate("TaskDetailsDialog", "Закрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TaskDetailsDialog = QtWidgets.QDialog()
    ui = Ui_TaskDetailsDialog()
    ui.setupUi(TaskDetailsDialog)
    TaskDetailsDialog.show()
    sys.exit(app.exec_())
